name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: |
        docker build -t vps-test:${{ github.sha }} .
      
    - name: Push Docker image to registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push vps-test:${{ github.sha }}
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull vps-test:${{ github.sha }}
          docker stop vps-test || true
          docker rm vps-test || true
          docker run -d --name vps-test -p 80:80 vps-test:${{ github.sha }}
